enable python 3.13t (freethreading) in binary validation workflow
Summary:
# context
* python 3.13t was never supported in the github "binary validation" workflow due to lack of conda native support
```
$ conda create -n py313t python=3.13t
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - python=3.13t

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```
* therefore the validation workflow for python3.13t is alway skipped (early return)
```
if [[ ${MATRIX_PYTHON_VERSION} = '3.13t' ]]; then
    echo "Conda doesn't support 3.13t yet, you can just try \`conda create -n test python=3.13t\`"
    exit 0
fi
```
* the workaround is to use conda-forge channel to get the freethreading python
https://conda-forge.org/blog/2024/09/26/python-313/
```
conda create -n py313 python=3.13 python-freethreading -c conda-forge
```

Differential Revision: D76109652