Remove final typing import (#865)
Summary:
Pull Request resolved: https://github.com/pytorch/torchrec/pull/865

torchrec/metrics/rec_metric.py:17: in <module>
    from typing import (
E   ImportError: cannot import name 'Final' from 'typing' (/opt/conda/envs/build_binary/lib/python3.7/typing.py)

since we need to support 3.7

Reviewed By: renganxu

Differential Revision: D41774345

fbshipit-source-id: 70cb7e0ec58fdf1715305751f3fc582e24e10107