Avoid nan by using zeros instead of empty dummy tensor (#2648)
Summary:

This appears to solve the nan issue when we enable
`torch.autograd.set_detect_anomaly(True)`

The error below appears non-deterministically, and after a few training steps, presumably because `self._dummy_tensor` can be very large but not nan at the beginning, and after a few iterations reaches `nan`.

```
RuntimeError: Function 'All2All_Seq_Req_WaitBackward' returned nan values in its 0th output; num_outputs = 1; num_inputs = 0; outputs[0].shape = [1, ]; outputs[i] = nan

[ torch.cuda.FloatTensor{1} ]
```

Reviewed By: iamzainhuda

Differential Revision: D67535635