Embedding_modules change dtype to always be uint8 (#545)
Summary:
Pull Request resolved: https://github.com/pytorch/torchrec/pull/545

Crashing predictor with this crash:

```
std::runtime_error: Exception Caught inside torch::deploy embedded library:
NotImplementedError: Could not run 'aten::empty.SymInt' with arguments from the 'QuantizedMeta' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build).

At:
  <torch_package_0>.torchrec/quant/embedding_modules.py(69): quantize_state_dict
...
```

Reviewed By: zyan0

Differential Revision: D38155111

fbshipit-source-id: bc02abf6d0d417b4a88f353a578d064de8bf7aed