Fix Github Generate documentation runner (#2979)
Summary:

# context
* TorchRec Github [Generate documentation Action](https://github.com/pytorch/torchrec/actions/runs/15041834069/job/42275145381) has been hanging forever due to out-dated the linux runner version.
{F1978070884}
* change the linux runner from `linux.20_04.4x` to `linux.24_04.4x`

NOTE: removed pip upgrade due to the following error
```
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 24.0
ERROR: Cannot uninstall pip 24.0, RECORD file not found. Hint: The package was installed by debian.
Error: Process completed with exit code 1.
```

Differential Revision: D74971871