and LB_LIBRARY_PATH for cpu case in install_fbgemm.sh (#2699)
Summary:
Pull Request resolved: https://github.com/pytorch/torchrec/pull/2699

# context
* `LB_LIBRARY_PATH` is missing the required path for cpu case, leading to test failure at https://github.com/pytorch/torchrec/actions/runs/12914965105
```
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /__w/_temp/conda_environment_12914965105/lib/python3.12/site-packages/tensordict/_C.so)
```
* this diff adding the missing branch when there is only cpu available

Reviewed By: vmoens

Differential Revision: D68524715

fbshipit-source-id: dee105434c3beae58fe9c4f1cde07833406f4c76