copy `is_non_strict_exporting` over to resolve backward compatibility issue
Summary:
# context
* An ImportError was reported
```
ImportError: cannot import name 'register_custom_op' from 'torchrec.modules.utils'
```
* it's due to previously introduced function at D56443608
* test failed: https://www.internalfb.com/intern/test/562950051370255/
```
Mitigation: ImportError("cannot import name 'is_non_strict_exporting' from '<torch_package_1>.torchrec.sparse.jagged_tensor' (<torch_package_1>.torchrec/sparse/jagged_tensor.py)")
```

Reviewed By: IvanKobzarev, drdarshan

Differential Revision: D56578871

fbshipit-source-id: 3f447cac2946ac8b270848c0067bf990f3e31707