Fix forward for D51601041 (#1671)
Summary:
Pull Request resolved: https://github.com/pytorch/torchrec/pull/1671

D51601041 causes a torch package backward compatibility problem, this diff imports ComputeJTDictToKJT which creates a new dependency from torchrec/modules to torchrec/sparse, since the problem module was built a while ago, it has torchrec/sparse inside torch package but doesn't have torchrec/modules, it encounters this error, https://fburl.com/mlhub/f8be5yru

> ImportError("cannot import name 'ComputeJTDictToKJT' from '<torch_package_1>.torchrec.sparse.jagged_tensor'

This diff did a lazy import so that only model with zch enabled will use this

Reviewed By: dstaay-fb

Differential Revision: D53208002

fbshipit-source-id: c48d388c06b0fbd6ab603ac14d02c60557fb78cc