Break circular dependency on KeyedOptimizer (#2030)
Summary:
Pull Request resolved: https://github.com/pytorch/torchrec/pull/2030

There is a circular dependency between `torchrec.optim` and `torchrec.distributed`. Example failure trace:
```
from torchrec.optim.keyed import KeyedOptimizer, OptimizerWrapper
  File "/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/buck-out/v2/gen/fbcode/f6ce11a18cff399f/apf_cli/compare/tests/__command_test__/command_test#link-tree/torchrec/optim/__init__.py", line 23, in <module>
    from torchrec.optim.clipping import GradientClipping, GradientClippingOptimizer  # noqa
  File "/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/buck-out/v2/gen/fbcode/f6ce11a18cff399f/apf_cli/compare/tests/__command_test__/command_test#link-tree/torchrec/optim/clipping.py", line 14, in <module>
    from torchrec.optim.keyed import KeyedOptimizer, OptimizerWrapper
  File "/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/buck-out/v2/gen/fbcode/f6ce11a18cff399f/apf_cli/compare/tests/__command_test__/command_test#link-tree/torchrec/optim/keyed.py", line 29, in <module>
    from torchrec.distributed.types import ShardedTensor
  File "/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/buck-out/v2/gen/fbcode/f6ce11a18cff399f/apf_cli/compare/tests/__command_test__/command_test#link-tree/torchrec/distributed/__init__.py", line 38, in <module>
    from torchrec.distributed.model_parallel import DistributedModelParallel  # noqa
  File "/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/buck-out/v2/gen/fbcode/f6ce11a18cff399f/apf_cli/compare/tests/__command_test__/command_test#link-tree/torchrec/distributed/model_parallel.py", line 26, in <module>
    from torchrec.distributed.planner import EmbeddingShardingPlanner, Topology
  File "/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/buck-out/v2/gen/fbcode/f6ce11a18cff399f/apf_cli/compare/tests/__command_test__/command_test#link-tree/torchrec/distributed/planner/__init__.py", line 24, in <module>
    from torchrec.distributed.planner.planners import EmbeddingShardingPlanner  # noqa
  File "/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/buck-out/v2/gen/fbcode/f6ce11a18cff399f/apf_cli/compare/tests/__command_test__/command_test#link-tree/torchrec/distributed/planner/planners.py", line 22, in <module>
    from torchrec.distributed.planner.enumerators import EmbeddingEnumerator
  File "/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/buck-out/v2/gen/fbcode/f6ce11a18cff399f/apf_cli/compare/tests/__command_test__/command_test#link-tree/torchrec/distributed/planner/enumerators.py", line 30, in <module>
    from torchrec.distributed.sharding_plan import calculate_shard_sizes_and_offsets
  File "/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/buck-out/v2/gen/fbcode/f6ce11a18cff399f/apf_cli/compare/tests/__command_test__/command_test#link-tree/torchrec/distributed/sharding_plan.py", line 19, in <module>
    from torchrec.distributed.embedding import EmbeddingCollectionSharder
  File "/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/buck-out/v2/gen/fbcode/f6ce11a18cff399f/apf_cli/compare/tests/__command_test__/command_test#link-tree/torchrec/distributed/embedding.py", line 35, in <module>
    from torchrec.distributed.sharding.cw_sequence_sharding import (
  File "/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/buck-out/v2/gen/fbcode/f6ce11a18cff399f/apf_cli/compare/tests/__command_test__/command_test#link-tree/torchrec/distributed/sharding/cw_sequence_sharding.py", line 14, in <module>
    from torchrec.distributed.embedding_lookup import (
  File "/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/buck-out/v2/gen/fbcode/f6ce11a18cff399f/apf_cli/compare/tests/__command_test__/command_test#link-tree/torchrec/distributed/embedding_lookup.py", line 27, in <module>
    from torchrec.distributed.batched_embedding_kernel import (
  File "/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/buck-out/v2/gen/fbcode/f6ce11a18cff399f/apf_cli/compare/tests/__command_test__/command_test#link-tree/torchrec/distributed/batched_embedding_kernel.py", line 62, in <module>
    from torchrec.optim.fused import (
  File "/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/buck-out/v2/gen/fbcode/f6ce11a18cff399f/apf_cli/compare/tests/__command_test__/command_test#link-tree/torchrec/optim/fused.py", line 14, in <module>
    from torchrec.optim.keyed import KeyedOptimizer
ImportError: cannot import name 'KeyedOptimizer' from partially initialized module 'torchrec.optim.keyed' (most likely due to a circular import) (/data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/buck-out/v2/gen/fbcode/f6ce11a18cff399f/apf_cli/compare/tests/__command_test__/command_test#link-tree/torchrec/optim/keyed.py)
```

Reviewed By: dstaay-fb

Differential Revision: D57656790

fbshipit-source-id: d3c440a08c8f2008e01637983f0f8c3c71f9bc14