Fix `ModuleNotFoundError` error in introduction notebook when calling `apply_overlapped_optimizer` (#1070)
Summary:
Currently, running the `Torchrec_Introduction.ipynb` notebook through, without modifications, will lead to the following error about halfway down:

```python
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[14], line 1
----> 1 from torchrec.optim.apply_overlapped_optimizer import apply_overlapped_optimizer
      3 apply_overlapped_optimizer(
      4     ebc.parameters(),
      5     optimizer_type=torch.optim.SGD,
      6     optimizer_kwargs={"lr": 0.02},
      7 )

ModuleNotFoundError: No module named 'torchrec.optim.apply_overlapped_optimizer'
```

The `apply_overlapped_optimizer ` function was renamed to `apply_optimizer_in_backward` in https://github.com/pytorch/torchrec/pull/728. This PR makes the small update to this notebook to reflect this change. **The functionality of this cell is the same, just updated to use the new function name and syntax.**

Pull Request resolved: https://github.com/pytorch/torchrec/pull/1070

Reviewed By: s4ayub

Differential Revision: D44064709

Pulled By: joshuadeng

fbshipit-source-id: 2dcc1c12885cfdca7d66816cfa4775ecce7d152f