fix upload-artifact v4 issue in build dynamic embedding wheel (#2754)
Summary:
Pull Request resolved: https://github.com/pytorch/torchrec/pull/2754

# context
* TorchRec's OSS workflow "build dynamic embedding wheels" has been [failing](https://github.com/pytorch/torchrec/actions/runs/13416363464/job/37478091546) due to an upgrading of upload action [bug report](https://github.com/actions/upload-artifact/issues/506)
* we saw similar error message as below
```
Run actions/upload-artifact@v4
With the provided path, there will be 1 file uploaded
Artifact name is valid!
Root directory input is valid!
Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
```

# solution
* as described in this [migration.md](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md), adding additional job (merge) the artifacts.

Reviewed By: aliafzal

Differential Revision: D69904715

fbshipit-source-id: 6c84275fd6753fe7887fa26ea4c3817b8ab551c1