Fix invalid record_stream arg for Request awaitable
Summary:
https://github.com/pytorch/torchrec/pull/2598 causes failures when running on cpu:

```
RuntimeError: unknown parameter type
```

This is because `record_stream` doesn't accept CPU streams. This diff forward fixes the issue.

Differential Revision: D67171994