Fix Github Generate documentation runner (#2979)
Summary:
Pull Request resolved: https://github.com/pytorch/torchrec/pull/2979

# context
* TorchRec Github [Generate documentation Action](https://github.com/pytorch/torchrec/actions/runs/15041834069/job/42275145381) has been hanging forever due to out-dated the linux runner version.
{F1978070884}
* change the linux runner from `linux.20_04.4x` to `linux.24_04.4x`

NOTE: pip upgrade command is also modified for the following reason:
> If you need to upgrade pip, do it through the system package manager. For example, use sudo apt update and then sudo apt upgrade python3-pip.
Avoid using pip install --upgrade pip if pip was originally installed by your OS's package manager. This can lead to conflicting versions and errors.
```
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 24.0
ERROR: Cannot uninstall pip 24.0, RECORD file not found. Hint: The package was installed by debian.
Error: Process completed with exit code 1.
```

Reviewed By: spmex

Differential Revision: D74971871

fbshipit-source-id: 7b0e805557f7a1ddc3f89d239a3ad987dba6bc1a