filter out py3.14 and cu130
Summary:
# context
* based on fbgemm v1.3.0, the cuda version are 12.6, 12.8, and 12.9
```
The packages are now available for download and test:

# PyTorch PIP (download.pytorch.org, recommended)
pip install --pre fbgemm-gpu==1.3.0 --index-url https://download.pytorch.org/whl/test/cpu/
pip install --pre fbgemm-gpu==1.3.0 --index-url https://download.pytorch.org/whl/test/cu126/
pip install --pre fbgemm-gpu==1.3.0 --index-url https://download.pytorch.org/whl/test/cu128/
pip install --pre fbgemm-gpu==1.3.0 --index-url https://download.pytorch.org/whl/test/cu129/

# PyPI
pip install fbgemm-gpu==1.3.0rc2
pip install fbgemm-gpu-cpu==1.3.0rc2
pip install fbgemm-gpu-genai==1.3.0rc2
```
* also python 3.14 seems not work
```
[hhy@devgpu001.ash8 ~/local]$ conda create -yn py314 python=3.14 -c=conda-forge
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                  

UnsatisfiableError: The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.34=0
  - python=3.14 -> __glibc[version='>=2.17,<3.0.a0']

Your installed version is: 2.34
```

Differential Revision: D81467034