Fix invalid record_stream arg for Request awaitable (#2634)
Summary:
Pull Request resolved: https://github.com/pytorch/torchrec/pull/2634

https://github.com/pytorch/torchrec/pull/2598 causes failures when running on cpu:

```
RuntimeError: unknown parameter type
```

This is because `record_stream` doesn't accept CPU streams. This diff forward fixes the issue.

Differential Revision: D67171994

fbshipit-source-id: a9ffddfcd978d343a58fb039a4fcd89c336ceee6